export enum AbilityType {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
}

export enum AbilityName {
  USER_READ = 'USER:READ',
  USER_UPDATE = 'USER:UPDATE',
  ROLE_CREATE = 'ROLE:CREATE',
  ROLE_READ = 'ROLE:READ',
  ROLE_UPDATE = 'ROLE:UPDATE',
  ROLE_DELETE = 'ROLE:DELETE',
  CATEGORY_CREATE = 'CATEGORY:CREATE',
  CATEGORY_READ = 'CATEGORY:READ',
  CATEGORY_UPDATE = 'CATEGORY:UPDATE',
  CATEGORY_DELETE = 'CATEGORY:DELETE',
  CATEGORY_PROPERTY_CREATE = 'CATEGORY_PROPERTY:CREATE',
  CATEGORY_PROPERTY_READ = 'CATEGORY_PROPERTY:READ',
  CATEGORY_PROPERTY_UPDATE = 'CATEGORY_PROPERTY:UPDATE',
  CATEGORY_PROPERTY_DELETE = 'CATEGORY_PROPERTY:DELETE',
}
