export enum AbilityType {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
}

export enum AbilityName {
  USER_READ = 'USER:READ',
  USER_UPDATE = 'USER:UPDATE',
  USER_TYPE_UPDATE = 'USER_TYPE:UPDATE',
  USER_ROLES_UPDATE = 'USER_ROLES:UPDATE',
  ROLE_CREATE = 'ROLE:CREATE',
  ROLE_READ = 'ROLE:READ',
  ROLE_UPDATE = 'ROLE:UPDATE',
  ROLE_DELETE = 'ROLE:DELETE',
  CATEGORY_CREATE = 'CATEGORY:CREATE',
  CATEGORY_READ = 'CATEGORY:READ',
  CATEGORY_UPDATE = 'CATEGORY:UPDATE',
  CATEGORY_DELETE = 'CATEGORY:DELETE',
  PRODUCT_CREATE = 'PRODUCT:CREATE',
  PRODUCT_READ = 'PRODUCT:READ',
  PRODUCT_UPDATE = 'PRODUCT:UPDATE',
  PRODUCT_DELETE = 'PRODUCT:DELETE',
}
