export type Icon =
  | 'add-2-rounded'
  | 'arrow-downward-alt-rounded'
  | 'arrow-upward-alt-rounded'
  | 'category-rounded'
  | 'chevron-left-rounded'
  | 'close-rounded'
  | 'dashboard-rounded'
  | 'delete-rounded'
  | 'enterprise'
  | 'eye-tracking-rounded'
  | 'ink-pen-rounded'
  | 'loading'
  | 'menu-rounded'
  | 'supervised-user-circle';
